apiVersion: apps/v1
kind: Deployment
metadata:
 name: ui-depl
 labels:
    app: ui
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ui
 template:
  metadata:
   labels:
     app: ui
  spec:
    containers:
     - name: ui
       image: sunilmkamble17/ui
       ports:
       - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: ui-srv
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200

